kind: Deployment
apiVersion: apps/v1
metadata:
  name: secret-protection-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-protection-controller
  template:
    metadata:
      labels:
        app: secret-protection-controller
    spec:
      serviceAccount: secret-protection-controller
      containers:
        - name: secret-protection-controller
          image: secret-protection-controller:latest
          args:
            - "--v=5"
              #- "--resyncPeriod=30s"
          imagePullPolicy: IfNotPresent
